---
self-contained: true
title: "Lab 3 - 12 Days of Christmas"
format:
  html:
    theme: journal
---

In [567]:
import pandas as pd
import numpy as np

# Christmas dataset

In [568]:
xmas = pd.read_csv("https://www.dropbox.com/scl/fi/qxaslqqp5p08i1650rpc4/xmas.csv?rlkey=erdxi7jbh7pqf9fh4lv4cayp5&dl=1")
xmas

    Day Day.in.Words  Gift.Item        Verb Adjective        Location
0     1        first  partridge         NaN       NaN  in a pear tree
1     2       second       dove         NaN    turtle             NaN
2     3        third        hen         NaN    french             NaN
3     4       fourth       bird         NaN   calling             NaN
4     5        fifth       ring         NaN    golden             NaN
5     6        sixth      goose    a-laying       NaN             NaN
6     7      seventh       swan  a-swimming       NaN             NaN
7     8       eighth       maid   a-milking       NaN             NaN
8     9        ninth       lady     dancing       NaN             NaN
9    10        tenth       lord   a-leaping       NaN             NaN
10   11     eleventh      piper      piping       NaN             NaN
11   12      twelfth    drummer    drumming       NaN             NaN

# Function to pluralize gift items

In [569]:
#pluralize_gift function
#if has oo, replace oo with ee
#if ends with y, replace y with ies
#if does not have any of these, add s to end

def pluralize_gift(gift):
    """
   Returns plural of a noun
    Parameters
    ----------
    gift: str
    A noun
    Return
    ------
    str
    Plural version
    """
    if ("oo" in gift):
        gift = gift.replace("oo", "ee")
    elif gift[-1] == ("y"): 
        gift = gift.replace("y", "ies")
    else:
        gift = gift + "s"
    return gift

### Unit Testing

In [570]:
#using numpy vectorize to vectorize pluralize_gift function
vec_pluralize_gift = np.vectorize(pluralize_gift)

In [571]:
#unit testing
pluralize_gift("lady")

'ladies'

In [572]:
#unit testing
pluralize_gift("goose")

'geese'

In [573]:
#unit testing
pluralize_gift("drummer")

'drummers'

In [574]:
#unit testing
vec_pluralize_gift(xmas["Gift.Item"])

array(['partridges', 'doves', 'hens', 'birds', 'rings', 'geese', 'swans',
       'maids', 'ladies', 'lords', 'pipers', 'drummers'], dtype='<U10')

# Function to make the phrases of the song

In [575]:
#function 2: make_phrase()
def make_phrase(num, num_word, item, verb, adjective, location):
    """
    Returns the phrase of a line
    Parameters
    ------------
    num: int
        the actual number for the day
    num_word: str
        change the number from int to the actual word
    item: str
        the gift item that is pluralized (from function above)
    verb: str
        verb describing the gift item 
    adjective: str
        adjective describing gift item, goes before item
    location: str
        a phrase describing only the patridge
    
    Return
    ------------
    str of all the pieces together
    """
    #dictionary called number_to_word; key = number, value = actual word of number
    number_to_word = {
        "first": "one",
        "second": "two",
        "third": "three",
        "fourth": "four",
        "fifth": "five",
        "sixth": "six",
        "seventh": "seven",
        "eighth": "eight",
        "ninth": "nine",
        "tenth": "ten",
        "eleventh": "eleven",
        "twelfth": "twelve"
        }
  
  ## Step 1: Replace NAs with blank strings
    if pd.isna(verb):
        verb = ""
    if pd.isna(adjective):
        adjective = ""
    if pd.isna(location):
        location = ""
  
  ## Step 2: If the day number is larger than 1, the gift items need pluralized!
  ### Hint: call the function you created above!
    
    #if num (day) is greater than 1
    if num > 1:
        item = pluralize_gift(item) #pluralize the item
        
    #need to use word form of number, so get it from the dictionary
    num_word = number_to_word.get(num_word)
    
  ## Step 3: Figure out if a gift item starts with a vowel
    vowel = ["a", "e", "i", "o", "u"] #list of vowels
  
  ## Step 4: For the first day, if the gift item starts with a vowel, replace the day with "an" 
    if num == 1 and item[0] in vowel:
        num_word = "an" #make sure i am not using .replace to replace anything in the dictionary, so just let it equal "an" or "a"
    elif num == 1:
        num_word = "a"
    
    #put all variables into a list so you can use join to join them together
    phrase_list = [num_word, adjective, item, verb, location] #list of all of the variables
    phrase = " ".join([word for word in phrase_list if word]) #join them together, remove any extra white space

    return phrase

### Unit Testing

In [576]:
#testing make_phrase function
print(make_phrase(num = 1, num_word = "first", item = "apple", verb = "a-laying", adjective = "golden", location = "in a pear tree"))

an golden apple a-laying in a pear tree

## Apply make_phrase function to all of the columns in the xmas dataset

In [577]:
#apply make_phrase function to all of the columns in xmas
xmas["Full.Phrase"] = xmas.apply(lambda x: make_phrase(x["Day"],
                                                       x["Day.in.Words"],
                                                       x["Gift.Item"],
                                                       x["Verb"],
                                                       x["Adjective"],
                                                       x["Location"]), axis=1)

In [578]:
xmas

,Day,Day.in.Words,Gift.Item,Verb,Adjective,Location,Full.Phrase
0,1,first,partridge,NaN,NaN,in a pear tree,a partridge in a pear tree
1,2,second,dove,NaN,turtle,NaN,two turtle doves
2,3,third,hen,NaN,french,NaN,three french hens
3,4,fourth,bird,NaN,calling,NaN,four calling birds
4,5,fifth,ring,NaN,golden,NaN,five golden rings
5,6,sixth,goose,a-laying,NaN,NaN,six geese a-laying
6,7,seventh,swan,a-swimming,NaN,NaN,seven swans a-swimming
7,8,eighth,maid,a-milking,NaN,NaN,eight maids a-milking
8,9,ninth,lady,dancing,NaN,NaN,nine ladies dancing
9,10,tenth,lord,a-leaping,NaN,NaN,ten lords a-leaping
10,11,eleventh,piper,piping,NaN,NaN,eleven pipers piping
11,12,twelfth,drummer,drumming,NaN,NaN,twelve drummers drumming

# Function to sing the song starting at a given day

In [579]:
#sing_phrase function, given a dataset, sing the song starting at num
def sing_day(dataset, num, phrase_col):
    """
    Returns the phrase of a line
    
    Parameters
    ------------
    dataset: pandas dataframe
        functions need to run through dataset
    num: int
        indicating what day to start the song
    phrase_col
        name of a column in the dataset that contains the phrases for each day: Full.Phrase
    
    Return verse
    ------------
    str of verse from that given day
    """
    
  # Step 1: Setup the intro line
    #1, 2, 3...etc --> first, second, third...etc.
    day_dict = xmas.set_index('Day')['Day.in.Words'].to_dict()
    word = day_dict.get(num)

    #Intro line
    intro = "On the " + word + " day of Christmas, my true love sent to me:"
    
  # Step 2: Sing the gift phrases - basically iterate through Full.Phrase column backwards

    list_of_gifts = dataset[phrase_col]
    gift = []
    for i in range(num-1, -1, -1): #from specified num to the very last number (1), counting down by 1
        gift_list = list_of_gifts.iloc[i].strip() #go to the specific row num and get the Full.Phrase value and add to gift_list, .strip to remove any leading empty space
        #chatgpt
        if i == 0 and num > 1: 
            gift_list = "and " + gift_list
        gift.append(gift_list)
        
  # Step 3: Put it all together and return
    verse = intro + "\n" + ",\n".join(gift) + "."
    return verse

In [580]:
#testing out sing_day
print(sing_day(xmas, 12, "Full.Phrase"))

On the twelfth day of Christmas, my true love sent to me:
twelve drummers drumming,
eleven pipers piping,
ten lords a-leaping,
nine ladies dancing,
eight maids a-milking,
seven swans a-swimming,
six geese a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves,
and a partridge in a pear tree.

# Sing the entire 12 Days of Christmas Song

In [581]:
#write the entire song
def sing_full_song(dataset, num, phrase_col):
    """
    Returns the full 12 Days of Christmas Song 
    
    Parameters
    ----------
    dataset: pandas df
        dataset given
    num: int
        an integer that represents the day to sing to
    phrase_col: pandas series
        a column that includes all of the phrases: Full.Phrase
        
    Returns full_song
    ----------
    str of the entire song
    
    """
    song = list(map(lambda given_day: sing_day(dataset, given_day, phrase_col), range(1, num + 1, 1))) #start at day 1, stop at num + 1 (there is no day 0)
    entire_song = "\n\n".join(song)
    return entire_song

In [582]:
print(sing_full_song(xmas, 12, "Full.Phrase"))

On the first day of Christmas, my true love sent to me:
a partridge in a pear tree.

On the second day of Christmas, my true love sent to me:
two turtle doves,
and a partridge in a pear tree.

On the third day of Christmas, my true love sent to me:
three french hens,
two turtle doves,
and a partridge in a pear tree.

On the fourth day of Christmas, my true love sent to me:
four calling birds,
three french hens,
two turtle doves,
and a partridge in a pear tree.

On the fifth day of Christmas, my true love sent to me:
five golden rings,
four calling birds,
three french hens,
two turtle doves,
and a partridge in a pear tree.

On the sixth day of Christmas, my true love sent to me:
six geese a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves,
and a partridge in a pear tree.

On the seventh day of Christmas, my true love sent to me:
seven swans a-swimming,
six geese a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves,
and a partridge in a pear tree.

On the eighth day of Christmas, my true love sent to me:
eight maids a-milking,
seven swans a-swimming,
six geese a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves,
and a partridge in a pear tree.

On the ninth day of Christmas, my true love sent to me:
nine ladies dancing,
eight maids a-milking,
seven swans a-swimming,
six geese a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves,
and a partridge in a pear tree.

On the tenth day of Christmas, my true love sent to me:
ten lords a-leaping,
nine ladies dancing,
eight maids a-milking,
seven swans a-swimming,
six geese a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves,
and a partridge in a pear tree.

On the eleventh day of Christmas, my true love sent to me:
eleven pipers piping,
ten lords a-leaping,
nine ladies dancing,
eight maids a-milking,
seven swans a-swimming,
six geese a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves,
and a partridge in a pear tree.

On the twelfth day of Christmas, my true love sent to me:
twelve drummers drumming,
eleven pipers piping,
ten lords a-leaping,
nine ladies dancing,
eight maids a-milking,
seven swans a-swimming,
six geese a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves,
and a partridge in a pear tree.

# Testing it out with a different dataset: xmas2

In [583]:
#read xmas2
xmas2 = pd.read_csv("https://www.dropbox.com/scl/fi/p9x9k8xwuzs9rhp582vfy/xmas_2.csv?rlkey=kvc3j3lmyn4opcidsrhcmrof1&dl=1")
xmas2

    Day Day.in.Words Gift.Item         Verb Adjective       Location
0     1        first     email          NaN       NaN  from Cal Poly
1     2       second     point          NaN      meal            NaN
2     3        third       pen          NaN      lost            NaN
3     4       fourth    review          NaN    course            NaN
4     5        fifth      exam          NaN  practice            NaN
5     6        sixth    grader      grading       NaN            NaN
6     7      seventh    senior    stressing       NaN            NaN
7     8       eighth       mom    a-calling       NaN            NaN
8     9        ninth     party      bumping       NaN            NaN
9    10        tenth      load   of laundry       NaN            NaN
10   11     eleventh    friend  goodbye-ing       NaN            NaN
11   12      twelfth      hour     sleeping       NaN            NaN

In [584]:
xmas2["Full.Phrase"] = xmas2.apply(lambda x: make_phrase(x["Day"],
                                                       x["Day.in.Words"],
                                                       x["Gift.Item"],
                                                       x["Verb"],
                                                       x["Adjective"],
                                                       x["Location"]), axis=1)

### Sing the entire xmas2 song!

In [585]:
print(sing_full_song(xmas2, 12, "Full.Phrase"))

On the first day of Christmas, my true love sent to me:
an email from Cal Poly.

On the second day of Christmas, my true love sent to me:
two meal points,
and an email from Cal Poly.

On the third day of Christmas, my true love sent to me:
three lost pens,
two meal points,
and an email from Cal Poly.

On the fourth day of Christmas, my true love sent to me:
four course reviews,
three lost pens,
two meal points,
and an email from Cal Poly.

On the fifth day of Christmas, my true love sent to me:
five practice exams,
four course reviews,
three lost pens,
two meal points,
and an email from Cal Poly.

On the sixth day of Christmas, my true love sent to me:
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points,
and an email from Cal Poly.

On the seventh day of Christmas, my true love sent to me:
seven seniors stressing,
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points,
and an email from Cal Poly.

On the eighth day of Christmas, my true love sent to me:
eight moms a-calling,
seven seniors stressing,
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points,
and an email from Cal Poly.

On the ninth day of Christmas, my true love sent to me:
nine parties bumping,
eight moms a-calling,
seven seniors stressing,
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points,
and an email from Cal Poly.

On the tenth day of Christmas, my true love sent to me:
ten loads of laundry,
nine parties bumping,
eight moms a-calling,
seven seniors stressing,
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points,
and an email from Cal Poly.

On the eleventh day of Christmas, my true love sent to me:
eleven friends goodbye-ing,
ten loads of laundry,
nine parties bumping,
eight moms a-calling,
seven seniors stressing,
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points,
and an email from Cal Poly.

On the twelfth day of Christmas, my true love sent to me:
twelve hours sleeping,
eleven friends goodbye-ing,
ten loads of laundry,
nine parties bumping,
eight moms a-calling,
seven seniors stressing,
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points,
and an email from Cal Poly.